// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGKyg33rOtvDdQ-CvAlHyyhEIZ2tQtPPU',
    appId: '1:267409898776:web:f73675ec8e97b70529726d',
    messagingSenderId: '267409898776',
    projectId: 'flutter-chat-app-290a6',
    authDomain: 'flutter-chat-app-290a6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-290a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRB60javbfDW7t-guIoRMEurdylb1jEwM',
    appId: '1:267409898776:android:3d61a8181e083c5329726d',
    messagingSenderId: '267409898776',
    projectId: 'flutter-chat-app-290a6',
    storageBucket: 'flutter-chat-app-290a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8S0_zxdw00tx6nahQ-U1hb4GwWqdCo4Q',
    appId: '1:267409898776:ios:1f6e7c98cfcc9ae229726d',
    messagingSenderId: '267409898776',
    projectId: 'flutter-chat-app-290a6',
    storageBucket: 'flutter-chat-app-290a6.appspot.com',
    iosClientId: '267409898776-phtieeqt08g4a0rdlck53fonamcb64aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8S0_zxdw00tx6nahQ-U1hb4GwWqdCo4Q',
    appId: '1:267409898776:ios:1f6e7c98cfcc9ae229726d',
    messagingSenderId: '267409898776',
    projectId: 'flutter-chat-app-290a6',
    storageBucket: 'flutter-chat-app-290a6.appspot.com',
    iosClientId: '267409898776-phtieeqt08g4a0rdlck53fonamcb64aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
